In [1]:
import numpy as np

In [2]:
# Define matrices
oneA = np.array([[-1, 2],
                    [3, 1]])

oneA_two = np.array([[0, 1, 3],
                    [2, -3, 5]])

# Perform matrix multiplication
result = np.dot(oneA, oneA_two)

print("Matrix 1:")
print(oneA)
print("\nMatrix 2:")
print(oneA_two)
print("\nResult of matrix multiplication:")
print(result)


Matrix 1:
[[-1  2]
 [ 3  1]]

Matrix 2:
[[ 0  1  3]
 [ 2 -3  5]]

Result of matrix multiplication:
[[ 4 -7  7]
 [ 2  0 14]]


In [3]:
oneB = np.array([[1, 3, 5],
                [0, -2, 1],
                [2, -1, 4]])

oneB_two = np.array([[1],
                    [-3],
                    [-1]])

# Perform matrix multiplication
result = np.dot(oneA, oneA_two)

print("Matrix 1:")
print(oneB)
print("\nMatrix 2:")
print(oneB_two)
print("\nResult of matrix multiplication:")
print(result)


Matrix 1:
[[ 1  3  5]
 [ 0 -2  1]
 [ 2 -1  4]]

Matrix 2:
[[ 1]
 [-3]
 [-1]]

Result of matrix multiplication:
[[ 4 -7  7]
 [ 2  0 14]]


In [4]:
oneC = np.array([[2, 0, 1],
                [1, -3, 4],
                [0, 1, 5]])

oneC_two = np.array([[3],
                    [-5],
                    [7]])

# Perform matrix multiplication
result = np.dot(oneA, oneA_two)

print("Matrix 1:")
print(oneC)
print("\nMatrix 2:")
print(oneC_two)
print("\nResult of matrix multiplication:")
print(result)


Matrix 1:
[[ 2  0  1]
 [ 1 -3  4]
 [ 0  1  5]]

Matrix 2:
[[ 3]
 [-5]
 [ 7]]

Result of matrix multiplication:
[[ 4 -7  7]
 [ 2  0 14]]


In [5]:
oneD = np.array([[1, -4, 2],
                [3, 0, -2],
                [2, 1, 0]])

oneD_two = np.array([[5, 1, -1],
                    [-2, 1, 3],
                    [0, 3, 4]])

# Perform matrix multiplication
result = np.dot(oneA, oneA_two)

print("Matrix 1:")
print(oneD)
print("\nMatrix 2:")
print(oneD_two)
print("\nResult of matrix multiplication:")
print(result)


Matrix 1:
[[ 1 -4  2]
 [ 3  0 -2]
 [ 2  1  0]]

Matrix 2:
[[ 5  1 -1]
 [-2  1  3]
 [ 0  3  4]]

Result of matrix multiplication:
[[ 4 -7  7]
 [ 2  0 14]]
